// app/layout.js
import "./globals.css";
import { MatchProvider } from "./context/MatchContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MatchProvider>{children}</MatchProvider>
      </body>
    </html>
  );
}
